export const ERROR_CODES = {
  ROOM_FULL: 'ROOM_FULL',
  ALREADY_KICKED: 'ALREADY_KICKED',
};

export const ACTION_FLAGS = {
  // TYPE
  REQUEST: 0b0,
  RESPONSE: 0b1,

  // RESPONSE_TYPE
  ARRAYBUF_PAYLOAD: 0b000,
  BSON_PAYLOAD: 0b100,
};

export const PLAYER_ACTIONS = {
  PLAYER_INFO: 0,
  JOIN_ROOM: 1,
};
