export const ERROR_CODES = {
  ROOM_FULL: 'ROOM_FULL',
  ROOM_ALREADY_EXISTS: 'ROOM_ALREADY_EXISTS',
  ALREADY_KICKED: 'ALREADY_KICKED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  RACING_ALREADY_ACTIVE: 'RACING_ALREADY_ACTIVE',
};

export const ACTION_FLAGS = {
  // TYPE
  REQUEST: 0b0,
  RESPONSE: 0b1,

  // RESPONSE_TYPE
  ARRAYBUF_PAYLOAD: 0b000,
  BSON_PAYLOAD: 0b100,
};

export const PLAYER_TYPES = {
  BOT: 1,
  HUMAN: 2,
};

export const PLAYER_ACTIONS = {
  PLAYER_INFO: 0,
  JOIN_ROOM: 1,
  SEND_KEYMAP: 2,

  // GLOBAL ROOM METHODS
  START_ROOM_RACE: 3,

  // BROADCAST
  PLAYER_JOINED_TO_ROOM: 3,
  PLAYER_LEFT_ROOM: 4,
  UPDATE_PLAYERS_ROOM_STATE: 5,

  // HIGH LATENCY BROADCAST
  UPDATE_PLAYERS_RACE_STATE: 6,
  UPDATE_RACE_STATE: 7,

  // LOW LATENCY BROADCAST
  UPDATE_BOARD_OBJECTS: 8,

  // PING CHECK
  PING: 9,
};

export const CAR_TYPES = {
  RED: 0,
  BLUE: 1,
};

export const CAR_ALIGN = {
  CENTER: 0,
  LEFT_CORNER: 1,
  RIGHT_CORNER: -1,
};

export const OBJECT_TYPES = {
  PRIMITIVE: 0,
  ROAD: 1,
  TERRAIN: 2,
  PLAYER: 3,
  MESH: 4,
};

export const RACE_STATES = {
  WAIT_FOR_SERVER: 1,
  COUNT_TO_START: 2,
  RACE: 3,
  ALL_FINISH: 4,
};

export const PLAYER_RACE_STATES = {
  RACE: 1 << 0,
  WRONG_DIRECTION: 1 << 1,
  FINISH: 1 << 2,
};
